---
title: "Data manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```


## Look in the FAS litters data

```{r}
litters_df= read_csv("./data/FAS_litters.csv")
litters_df= janitor::clean_names(litters_df)
litters_df
```


## 'select'

Choose some columns and not others

```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```
（':' 从A-B列）


```{r}
select(litters_df, -litter_number)
```
（‘-’ 删去某一列）



Rename columns

```{r}
select(litters_df,GROUP = group, LITTer_NUmBer = litter_number)
```
（只显示所选列并重命名）


```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```
（显示所有内容，并重命名所选列）



Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```
（所选列会显示在第一列，其余所有内容显示在后）


```{r}
relocate(litters_df, litter_number)
```
（将选择的列locate到第一列）




## 'filter'

```{r}
filter(litters_df, gd0_weight<22)
```

```{r}
filter(litters_df, gd0_weight>=22)
```

```{r}
filter(litters_df, gd_of_birth ==20)
```

```{r}
filter(litters_df, !gd_of_birth ==20)
```
(！除了...)



```{r}
filter(litters_df, gd0_weight>=22, gd_of_birth ==20)
```


```{r}
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8") )
```



## 'arrange'

```{r}
arrange(litters_df, pups_born_alive)
```



## 'mutate'添加新列或修改现有列

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

##'%>%'

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain=gd18_weight-gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df=
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(wt_gain=gd18_weight-gd0_weight) %>%
  drop_na(gd0_weight)
```


